---
title: "COMPASS_TEMPEST_TGW_2022_DataViz"
author: "Stephanie J. Wilson"
date: "2025-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggpubr)
library(dplyr)
library(plyr)
library(tidyverse)
library(tidyr)
```

## Read in all processed files and combine
```{r}
#read all non-event files and add an event time point 
con <- read.csv("2022 Processed Data/COMPASS_TEMPEST_TGW_202206_Control_Processed.csv")
fw <- read.csv("2022 Processed Data/COMPASS_TEMPEST_TGW_202206_FW_Processed.csv")
sw <- read.csv("2022 Processed Data/COMPASS_TEMPEST_TGW_202206_SW_Processed.csv")

#need to rename sapflux ID and tree ID to sapflux_or_tree_ID in all dataframes 
names(con)[names(con) == 'Tree_ID'] <- 'Sapflux_Tree_ID'
names(fw)[names(fw) == 'Tree_ID'] <- 'Sapflux_Tree_ID'
names(sw)[names(sw) == 'Tree_ID'] <- 'Sapflux_Tree_ID'


#combine into one dataframe 
alldat <- rbind(con, fw, sw)
head(alldat)


alldat1 <- alldat[, -c(1:3) ]
alldat1 <- alldat1 %>%  
  filter(!str_detect(Sample_ID, "MSM_TR"))

write.csv(alldat1, "2022 Processed Data/TEMPEST_TGW_2022_AllData.csv")

```

## Make list of those that need diluted and write out
```{r}


#subset by those that need to be diluted
dilutions <- subset(alldat, CH4_Flag == "Needs Dilution")

#write out file of the list 
write.csv(dilutions, "2022 Processed Data/TEMPEST_TGW_2022_SamplesToDilute.csv")


```



## Viz All data 
```{r}

alldata <- read.csv("2022 Processed Data/TEMPEST_TGW_2022_AllData.csv")
head(alldata)

alldata1 <- alldata %>%  
  filter(!str_detect(Sapflux_Tree_ID, "ATM"))


#add sample Tree spp to the data frame 
loci <- read.csv("TEMPEST_TGW_Sample_Locations.csv")
head(loci)

names(loci)[names(loci) == 'Sapflux_ID'] <- 'Sapflux_Tree_ID'

alldata2 <- merge(loci, alldata1, by=c("Sapflux_Tree_ID"))
head(alldata2)

#visualize data through time 
plot <- ggplot()+
  geom_point(data=alldata2, aes(x=Sample_Day, y=CH4_Conc_ppm_dilcorr, color=Sapflux_Tree_ID), size=2)+ 
  facet_wrap(~Sample_Plot, ncol=1, scales="free")+ 
  theme_bw()+ labs(x="Month", y="CH4 (ppm)") + theme(legend.title = element_blank())
plot

plota <- ggplot()+
  geom_point(data=alldata2, aes(x=Sample_Day, y=CH4_Conc_ppm_dilcorr, color=spp), size=2)+ 
  facet_wrap(~Sample_Plot, ncol=1, scales="free")+ 
  scale_color_manual(values=c("darkcyan", "deeppink", "black")) +
  theme_bw()+ labs(x="Month", y="CH4 (ppm)") + theme(legend.title = element_blank())
plota

plot1 <- ggplot()+
  geom_boxplot(data=alldata2, aes(x=Sample_Plot, y=CH4_Conc_ppm_dilcorr, color=Sample_Plot))+ 
  scale_color_manual(values=c("darkgreen", "darkblue", "red")) +
  theme_bw()+ labs(x="Plot", y="CH4 (ppm)") + theme(legend.title = element_blank())
plot1

plot2 <- ggplot()+
  geom_boxplot(data=alldata2, aes(x=spp, y=CH4_Conc_ppm_dilcorr, color=spp))+ 
  facet_wrap(~Sample_Plot, ncol=1, scales="free")+ 
  scale_color_manual(values=c("darkcyan", "deeppink", "black")) +
  theme_bw()+ labs(x="Plot", y="CH4 (ppm)") + theme(legend.title = element_blank())
plot2

```

