---
title: "QA/QC"
author: "Colin Wu"
date: "3/10/2021"
output: 
  html_document:
    df_print: paged
    #See https://bookdown.org/yihui/rmarkdown/html-document.html#data-frame-printing
    toc: yes
    toc_float: yes
    code_folding: hide
---
```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(scatterpie)
#knit_print.tibble <- lemon_print

knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, rows.print=20)
```

# Inventory
```{r inventory}
inventory <- read_csv("../Data/tree_inventory/inventory.csv")

#add column to indicate if a specific tree had significant growth fron 2019 to 2020
inventory <- inventory %>%
  mutate(Sig_growth_2020 = abs(DBH_2020-DBH_2019) > 0.5) %>%
  separate(Grid, c("X","Y"), sep=1)
inventory

summary(inventory)
```

# Long Table
```{r long data}
#used method for pivoting longer multiple columns from https://stackoverflow.com/questions/61367186/pivot-longer-into-multiple-columns

#Take all variables that end in a year and turn it into a categorical variable Type
long_inventory <- inventory %>% 
  filter(In_Plot == TRUE) %>%
  pivot_longer(grep(colnames(inventory), pattern=".*_\\d{4}"), names_pattern = "(.*)_(\\d{4})", names_to = c("Type","Year"), values_to = "val",  values_transform = list(val = as.character), names_transform = list(Year = as.integer))

#Unpack Type into seperate variables
long_inventory <- long_inventory %>% 
  pivot_wider(names_from = Type, values_from=val) %>%
  relocate(c(Tag, Year, Date, Status, Sig_growth, DBH))%>%
  mutate(DBH = as.numeric(DBH), Date = as.Date(Date, format = "%m/%d/%y"), 
         Sig_growth = as.logical(Sig_growth),
         BA = pi*(DBH/200)^2/0.2)

long_inventory
summary(long_inventory)
```

# Summary
```{r numtrees}
#create summary table that displays the number of trees of each species in each plot
summary_table <- inventory %>% 
  group_by(Plot, Species_code) %>% 
  summarize(num_trees = n())
summary_table

Tree_Live <- long_inventory %>% 
  filter(Status == "LI") %>% 
  group_by(Plot, Species_code, Year) %>% summarize(live_trees = n()) %>% 
  pivot_wider(names_from = Year, values_from =live_trees, names_prefix = "Live_Trees_")
Tree_Live

Stem_Live <- long_inventory %>% 
  group_by(Plot, Year) %>% 
  summarize(Alive = length(grep("LI", Status)), Dead = length(grep("D.", Status)))
Stem_Live

Stem_Standing <- long_inventory %>% 
  group_by(Year) %>%
  summarize(Standing = length(grep(".S|LI", Status)), Down = length(grep(".C", Status)))
Stem_Standing

Total_BA <- long_inventory %>% 
  group_by(Plot, Year) %>% 
  summarize(BA = sum(BA, na.rm=TRUE)) %>%
  pivot_wider(names_from = Year, values_from = BA, names_prefix = "BA_")
Total_BA

Mortality_Table <- long_inventory %>% arrange(Year) %>% group_by(Tag) %>% filter(lag(Status) == "LI" & grepl("D.", Status))
Mortality_Table
```

# Graphs
```{r graphs, fig.width=10,fig.height=10}
#BA_graph <- long_inventory %>% 
#  group_by(Year, Species_code, Plot) %>% 
#  summarize(BA = sum(BA)) %>% 
#  ggplot(aes(Year, BA, fill = Species_code)) +
#  geom_area() +
#  facet_wrap(~Plot)
#print(BA_graph)

Diam_Distr <- long_inventory %>% ggplot(aes(DBH)) + geom_density() + facet_grid(Year~Plot)
Diam_Distr
```
```{r scatterpie, fig.width=10,fig.height=20}
scatter_inventory <- inventory %>% 
  filter(!is.na(X) & !is.na(Y)) %>% 
  mutate(X=match(tolower(X), letters), Y= as.integer(Y)) %>%
  group_by(X, Y, Plot, Species_code) %>% 
  summarize(num_type = n()) %>%
  pivot_wider(names_from = Species_code, values_from=num_type)

#turn all NAs into 0s
scatter_inventory[is.na(scatter_inventory)] <- 0
#scatter_inventory

scatterpie_dist <- ggplot() + geom_scatterpie(aes(x = X, y = Y), data = scatter_inventory, cols = colnames(scatter_inventory)[-(1:3)]) + coord_equal() + facet_wrap(~Plot, ncol=1) 

scatterpie_dist
```

# Error Check {.tabset}
## Zombie Trees
```{r}
zombie_trees <- long_inventory %>%
  group_by(Tag) %>%
  filter(!all(sapply(which(Status == "LI"), function(x, y) all(x < y), which(Status != "LI"))))
zombie_trees
```

## Down to Standing Trees
```{r}
down_trees <- long_inventory %>% 
  group_by(Tag) %>%
  filter(!all(sapply(grep(".S|LI", Status), function(x, y) all(x < y), grep(".C", Status))))
down_trees
```

## Incorrect Status
```{r}
wrong_status <- long_inventory %>%
  group_by(Tag) %>%
  filter(!all(sapply(grep(NA, Status), function(x, y) all(x < y), grep(!NA, Status))) | (!grepl("LI|D[SC]", Status) & !is.na(Status))) %>% 
  select(Tag, Year, Status, Notes)
wrong_status
```

## Incorrect DBH
```{r}
bad_DBH <- long_inventory %>% filter(DBH < 1)
bad_DBH
```

