---
title: "Sapflow QA / QC"
author: "Stephanie Pennington"
date: "5/6/2021"
output: html_document
---

```{r setup}
# Load packages
library(readr)
library(lubridate)
library(dplyr)
library(tidyr)
library(ggplot2)

# Global chunk options
knitr:: opts_chunk$set(echo = FALSE)

# Function setup
read_sapflow <- function(filename) {
    sdat <- readLines(filename)
    sdat <- sdat[-3:-4] # remove lines 3 and 4 with unneeded information
    
    # parse line one to extract logger name
    pnnl_x <- gregexpr("PNNL_", sdat[1])[[1]][1]
    logger_name <- substr(sdat[1], start = pnnl_x, stop = pnnl_x + 6)
    
    read_csv(sdat, skip = 1) %>% 
        mutate(Logger = logger_name)
}

check_cycle <- function(dataframe) {
    # Takes in a dataframe and compares values or daytime and nighttime sapflow
    # Returns the dataframe with a new column 
    day <- 6:18
    night <- c(19, 20, 21, 22, 23, 24, 1, 2, 3, 4, 5)
    browser()
    dataframe %>% 
    mutate(DOY = yday(Timestamp), HOD = hour(Timestamp)) %>% 
    group_by(DOY) %>% 
    summarise(E3 = ifelse(Value[which(HOD %in% day)] < Value[which(HOD %in% night)]))
}

# Read in data
s_files <- list.files(path = "../Data/sapflow/", pattern = "PNNL", full.names = TRUE)
ports <- read_csv("../Design/ports.csv")

```

```{r process}

# pivot long
# extract number form former col name "DiffVolt_Avg(1)" would become "1"
# join with ports dataframe and bring in tree codes

lapply(s_files, read_sapflow) %>%  
    bind_rows() %>% 
    pivot_longer(cols = `DiffVolt_Avg(1)`:`DiffVolt_Avg(6)`, 
                 names_to = "Port", values_to = "Value") %>% 
    rename(Timestamp = TIMESTAMP, Record = RECORD) %>% 
    mutate(Timestamp = ymd_hms(Timestamp), 
           Port = parse_number(Port), 
           Logger = parse_number(Logger)) -> sf_raw

left_join(sf_raw, ports, by = c("Logger", "Port")) %>% 
    select(Timestamp, Record, BattV_Avg, Port, Value, Logger, Tree_Code, Species) -> sapflow

if(nrow(anti_join(sf_raw, ports, by = c("Logger", "Port"))) > 0) {
    warning("Error in join")
}

```


```{r qa/qc}

#Create test dataset
trees <- c("F16", "S15", "F2", "S6", "S2", "F13", "C10", "C11", "L4")

sapflow %>% 
    filter(Tree_Code %in% trees,
           Timestamp > "2021-04-25 12:30:00") -> test_df

sapflow %>% 
    mutate(E1 = !between(Value, 0, 1), # Value out of range
           E2 = is.na(Value)) -> t # Value NaN

# check for weird days
## daytime values > neighttime values
## midnight to 6 should look like 6 to midnight

# check for weird hours
## does 10am match up with +- 3 days
## does that meas fall btw previous and next measurement
    

```



```{r plots}


```

