---
title: "TEMPEST_Aquifer_WellTest_202511"
author: "Aquatroll 600 Data"
date: "2025-11-10"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(ggpubr)
library(dplyr)
library(plyr)
library(tidyverse)
library(tidyr)
library(lubridate)
library(knitr)
library(tibble)
library(patchwork)
```
## Aquatroll (AQ600) Well Data
```{r, echo=FALSE}
cat("In Situ AQ600 was put in one of the FW tanks while it was filled. 
    Data was recorded every minute for the duration of the test.")

well_dat <- read.csv("Raw Data/COMPASS_TEMPEST_WellTest_AQ600_Data_20251110.csv")
#head(well_dat)

#change column names in well_dat
colnames(well_dat) <- c("Date_Time", "DO_mgL", "DO_Sat", "DO_pp", "Actual_Conductivity_µScm" ,
                        "Specific_Conductivity_µScm", "Salinity_psu", "Resistivity_Ωcm", "Density_gcm", "TDS_ppt", 
                        "Temp_C", "Voltage_V", "Battery", "Baro_Press_mmHg", "Press_psi" ,"Depth_cm" ) 
#no pH data from this troll? "pH", "pH_mV" ,"ORP_mV",

#make date time actually a date and time with lubridate and remove extra data at the end 
well_dat$Date_Time <- mdy_hm(well_dat$Date_Time)

#remove data after aquatroll removed, remove salinity data lower than 0.001 and conductivity less than 1, 
#remove DO over 1 which was when AQ600 removed from water and any TDS lower than 0.1 also from AQ600 removal 
well_dat_filtered <- well_dat %>%
    filter(Date_Time < ymd_hms("2025-11-10 16:30:00")) %>%
    filter(Salinity_psu > 0.001) %>%
    filter(Specific_Conductivity_µScm > 1) %>%
    filter(DO_mgL < 5) %>%
    filter(TDS_ppt > 0.10) 

#create a table of average concentrations: 
all_summary_stats <- well_dat_filtered %>%
  summarise(
    Salinity_psu_mean = mean(Salinity_psu, na.rm = TRUE),
    Salinity_psu_sd = sd(Salinity_psu, na.rm = TRUE),
    Sp_Conductivity_µScm_mean = mean(Specific_Conductivity_µScm, na.rm = TRUE),
    Sp_Conductivity_µScm_sd = sd(Specific_Conductivity_µScm, na.rm = TRUE),
    DO_mgL_mean = mean(DO_mgL, na.rm = TRUE),
    DO_mgL_sd = sd(DO_mgL, na.rm = TRUE),
    TDS_ppt_mean = mean(TDS_ppt, na.rm = TRUE),
    TDS_ppt_sd = sd(TDS_ppt, na.rm = TRUE)
  ) %>%
  pivot_longer(
    everything(),
    names_to = c("Measurement", ".value"),
    names_sep = "_(?=[^_]+$)"  # Split at last underscore
  ) %>%
  mutate(mean = round(mean, 3), 
         sd = round(sd, 3)) 

cat("Summary of all AQ600 Measurements:")
kable(all_summary_stats)


#plot Salinity 
sal <- ggplot()+
  geom_point(data=well_dat_filtered, aes(x=Date_Time, y=Salinity_psu), size=2, color="blue")+ 
  theme_bw()+ labs(x="Time", y="Salinity (psu)", title="Aquifer Salinity") + theme(legend.title = element_blank())


#plot Conductivity 
cond <- ggplot()+
  geom_point(data=well_dat_filtered, aes(x=Date_Time, y=Specific_Conductivity_µScm), size=2, color="darkblue")+ 
  theme_bw()+ labs(x="Time", y="Specific Conductivity (µScm)", title="Aquifer Conductivity") + theme(legend.title = element_blank())

sal + cond

#plot DO
do <- ggplot()+
  geom_point(data=well_dat_filtered, aes(x=Date_Time, y=DO_mgL), size=2, color="darkred")+ 
  theme_bw()+ labs(x="Time", y="Dissolved Oxygen (mg/L)", title="Aquifer Dissolved Oxygen") + theme(legend.title = element_blank())


#plot TDS 
tds <- ggplot()+
  geom_point(data=well_dat_filtered, aes(x=Date_Time, y=TDS_ppt), size=2, color="darkgreen")+ 
  theme_bw()+ labs(x="Time", y="Total Dissolved Solids (ppt))", title="Aquifer TDS") + theme(legend.title = element_blank())

do + tds


#Pull out just the data from after things settle; after 12:45
well_dat_filtered_1 <- well_dat_filtered %>%
    filter(Date_Time > ymd_hms("2025-11-10 12:45:00"))

#create a table of average concentrations: 
summary_stats <- well_dat_filtered_1 %>%
  summarise(
    Salinity_psu_mean = mean(Salinity_psu, na.rm = TRUE),
    Salinity_psu_sd = sd(Salinity_psu, na.rm = TRUE),
    Sp_Conductivity_µScm_mean = mean(Specific_Conductivity_µScm, na.rm = TRUE),
    Sp_Conductivity_µScm_sd = sd(Specific_Conductivity_µScm, na.rm = TRUE),
    DO_mgL_mean = mean(DO_mgL, na.rm = TRUE),
    DO_mgL_sd = sd(DO_mgL, na.rm = TRUE),
    TDS_ppt_mean = mean(TDS_ppt, na.rm = TRUE),
    TDS_ppt_sd = sd(TDS_ppt, na.rm = TRUE)
  ) %>%
  pivot_longer(
    everything(),
    names_to = c("Measurement", ".value"),
    names_sep = "_(?=[^_]+$)"  # Split at last underscore
  ) %>%
  mutate(mean = round(mean, 3), 
         sd = round(sd, 3)) 

cat("Summary of AQ600 Measurements after 12:45 PM, after leveling out:")
kable(summary_stats)


```






